import mongoose from 'mongoose';
import Appointment from '../../../../../models/Appointment.js';
import PrescriptionGeneratedByDoctor from '../../../../../models/PrescriptionGeneratedByDoctor.js';
import '../../../../../models/PrescriptionItem.js';
import '../../../../../models/OrderItem.js';
import '../../../../../models/Medicine.js';

import Customer from '../../../../../models/Customer.js';

import { logDoctorActivity } from '../../../utils/logDoctorActivities.js';

/**
 * Check if doctor has authorization to view patient's medical history
 * @param {String} doctorId - The authenticated doctor's ID
 * @param {String} patientId - The patient/customer ID
 * @returns {Boolean} - True if authorized, false otherwise
 */
const checkDoctorAuthorization = async (doctorId, patientId) => {
  // Check if doctor has had at least one appointment with this patient
  const appointment = await Appointment.findOne({
    doctor_id: doctorId,
    patient_id: patientId,
  });

  return !!appointment;
};

/**
 * Build date filter object for queries
 * @param {String} startDate - ISO date string
 * @param {String} endDate - ISO date string
 * @returns {Object} - MongoDB date filter
 */
const buildDateFilter = (startDate, endDate) => {
  const dateFilter = {};

  if (startDate || endDate) {
    dateFilter.created_at = {};
    if (startDate) {
      dateFilter.created_at.$gte = new Date(startDate);
    }
    if (endDate) {
      dateFilter.created_at.$lte = new Date(endDate);
    }
  }

  return dateFilter;
};

/**
 * Fetch patient's past appointments for a specific doctor
 * @param {String} doctorId - The authenticated doctor's ID
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of appointments
 */
const fetchAppointments = async (doctorId, patientId, dateFilter) => {
  return await Appointment.find({
    doctor_id: doctorId,
    patient_id: patientId,
    status: { $in: ['completed', 'missed'] }, // Only past appointments
    ...dateFilter,
  })
    .populate('doctor_id', 'fullName email specialization')
    .populate('slot_id')
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch prescriptions generated by the authenticated doctor for a patient
 * @param {String} doctorId - The authenticated doctor's ID
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of prescriptions
 */
const fetchDoctorPrescriptions = async (doctorId, patientId, dateFilter) => {
  return await PrescriptionGeneratedByDoctor.find({
    doctor_id: doctorId,
    patient_id: patientId,
    ...dateFilter,
  })
    .populate('doctor_id', 'fullName email specialization')
    .populate('appointment_id', 'appointment_type status')
    .populate({
      path: 'prescription_items_ids',
      populate: {
        path: 'medicine_id',
        select: 'Name',
      },
    })
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch patient information
 * @param {String} patientId - The patient/customer ID
 * @returns {Object} - Patient details
 */
const fetchPatientInfo = async patientId => {
  return await Customer.findById(patientId)
    .select('fullName email gender dateOfBirth contactNumber profile_img_url')
    .lean();
};

/**
 * Fetch all patients treated by the doctor
 * @param {String} doctorId - The authenticated doctor's ID
 * @param {Object} query - Pagination/search query
 * @returns {Object} - Paginated patient list
 */
export const getDoctorPatientList = async (req, doctorId, query = {}) => {
  const page = Math.max(Number.parseInt(query.page || '1', 10) || 1, 1);
  const limit = Math.min(
    Math.max(Number.parseInt(query.limit || '20', 10) || 20, 1),
    100
  );
  const search = String(query.search || '')
    .trim()
    .toLowerCase();
  const skip = (page - 1) * limit;

  const groupedPatients = await Appointment.aggregate([
    {
      $match: {
        doctor_id: new mongoose.Types.ObjectId(doctorId),
      },
    },
    {
      $group: {
        _id: '$patient_id',
        total_appointments: { $sum: 1 },
        last_appointment_at: { $max: '$created_at' },
      },
    },
    {
      $sort: {
        last_appointment_at: -1,
      },
    },
  ]);

  const patientIds = groupedPatients.map(entry => entry._id).filter(Boolean);

  const patients = await Customer.find({
    _id: { $in: patientIds },
  })
    .select('fullName email contactNumber profile_img_url gender dateOfBirth')
    .lean();

  const patientMap = new Map(
    patients.map(patient => [String(patient._id), patient])
  );

  let patientList = groupedPatients
    .map(entry => {
      const patient = patientMap.get(String(entry._id));
      if (!patient) {
        return null;
      }

      return {
        ...patient,
        patient_id: patient._id,
        total_appointments: entry.total_appointments,
        last_appointment_at: entry.last_appointment_at,
      };
    })
    .filter(Boolean);

  if (search) {
    patientList = patientList.filter(patient => {
      const fullName = String(patient.fullName || '').toLowerCase();
      const email = String(patient.email || '').toLowerCase();
      return fullName.includes(search) || email.includes(search);
    });
  }

  const total = patientList.length;
  const paginatedPatients = patientList.slice(skip, skip + limit);

  await logDoctorActivity(
    req,
    'view_patients',
    `Viewed ${total} patient(s) treated by the doctor`,
    'customers',
    null,
    {
      filters: { page, limit, search },
      total_patients: total,
    }
  );

  return {
    patients: paginatedPatients,
    pagination: {
      current_page: page,
      total_pages: Math.ceil(total / limit),
      total_items: total,
      items_per_page: limit,
      has_next: page * limit < total,
      has_prev: page > 1,
    },
  };
};

/**
 * Get patient's complete medical history
 * @param {Object} req - Express request object
 * @param {String} patientId - The patient/customer ID
 * @param {String} startDate - Optional start date filter
 * @param {String} endDate - Optional end date filter
 * @returns {Object} - Aggregated medical history
 */
export const getPatientMedicalHistory = async (
  req,
  patientId,
  startDate,
  endDate
) => {
  const doctorId = req.doctor._id;

  // Step 1: Authorization check - ensure doctor has treated this patient
  const isAuthorized = await checkDoctorAuthorization(doctorId, patientId);
  if (!isAuthorized) {
    throw new Error(
      "UNAUTHORIZED_ACCESS: You do not have permission to view this patient's medical history"
    );
  }

  // Step 2: Build date filter
  const dateFilter = buildDateFilter(startDate, endDate);

  // Step 3: Fetch patient information
  const patientInfo = await fetchPatientInfo(patientId);
  if (!patientInfo) {
    throw new Error('PATIENT_NOT_FOUND: Patient not found');
  }

  // Step 4: Fetch all medical data in parallel
  const [appointments, doctorPrescriptions] = await Promise.all([
    fetchAppointments(doctorId, patientId, dateFilter),
    fetchDoctorPrescriptions(doctorId, patientId, dateFilter),
  ]);

  // Step 5: Extract medical notes from appointments
  const medicalNotes = appointments
    .filter(apt => apt.notes && apt.notes.trim() !== '')
    .map(apt => ({
      appointment_id: apt._id,
      appointment_date: apt.created_at,
      appointment_type: apt.appointment_type,
      notes: apt.notes,
      doctor: apt.doctor_id,
    }));

  // Step 6: Log the access for compliance
  await logDoctorActivity(
    req,
    'view_medical_history',
    `Viewed medical history for patient: ${patientInfo.fullName}`,
    'customers',
    patientId,
    {
      filters: { startDate, endDate },
      data_accessed: {
        appointments_count: appointments.length,
        prescriptions_count: doctorPrescriptions.length,
      },
    }
  );

  // Step 7: Return aggregated data
  return {
    patient: patientInfo,
    summary: {
      total_appointments: appointments.length,
      total_prescriptions_generated: doctorPrescriptions.length,
      total_medical_notes: medicalNotes.length,
    },
    history: {
      appointments,
      prescriptions_generated_by_doctor: doctorPrescriptions,
      medical_notes: medicalNotes,
    },
  };
};
