import Appointment from '../../../../../models/Appointment.js';
import PrescriptionGeneratedByDoctor from '../../../../../models/PrescriptionGeneratedByDoctor.js';
import '../../../../../models/PrescriptionItem.js';
import '../../../../../models/OrderItem.js';
import '../../../../../models/Medicine.js';

import PrescriptionUploadedByCustomer from '../../../../../models/PrescriptionUploadedByCustomer.js';
import Order from '../../../../../models/Order.js';

import Customer from '../../../../../models/Customer.js';

import { logDoctorActivity } from '../../../utils/logDoctorActivities.js';

/**
 * Check if doctor has authorization to view patient's medical history
 * @param {String} doctorId - The authenticated doctor's ID
 * @param {String} patientId - The patient/customer ID
 * @returns {Boolean} - True if authorized, false otherwise
 */
const checkDoctorAuthorization = async (doctorId, patientId) => {
  // Check if doctor has had at least one appointment with this patient
  const appointment = await Appointment.findOne({
    doctor_id: doctorId,
    patient_id: patientId,
  });

  return !!appointment;
};

/**
 * Build date filter object for queries
 * @param {String} startDate - ISO date string
 * @param {String} endDate - ISO date string
 * @returns {Object} - MongoDB date filter
 */
const buildDateFilter = (startDate, endDate) => {
  const dateFilter = {};

  if (startDate || endDate) {
    dateFilter.created_at = {};
    if (startDate) {
      dateFilter.created_at.$gte = new Date(startDate);
    }
    if (endDate) {
      dateFilter.created_at.$lte = new Date(endDate);
    }
  }

  return dateFilter;
};

/**
 * Fetch patient's past appointments
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of appointments
 */
const fetchAppointments = async (patientId, dateFilter) => {
  return await Appointment.find({
    patient_id: patientId,
    status: { $in: ['completed', 'missed'] }, // Only past appointments
    ...dateFilter,
  })
    .populate('doctor_id', 'fullName email specialization')
    .populate('slot_id')
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch prescriptions generated by doctors
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of prescriptions
 */
const fetchDoctorPrescriptions = async (patientId, dateFilter) => {
  return await PrescriptionGeneratedByDoctor.find({
    patient_id: patientId,
    ...dateFilter,
  })
    .populate('doctor_id', 'fullName email specialization')
    .populate('appointment_id', 'appointment_type status')
    .populate({
      path: 'prescription_items_ids',
      populate: {
        path: 'medicine_id',
        select: 'Name',
      },
    })
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch prescriptions uploaded by patient
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of uploaded prescriptions
 */
const fetchUploadedPrescriptions = async (patientId, dateFilter) => {
  return await PrescriptionUploadedByCustomer.find({
    patient_id: patientId,
    ...dateFilter,
  })
    .populate('order_id', 'status total')
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch patient's order history
 * @param {String} patientId - The patient/customer ID
 * @param {Object} dateFilter - Date filter object
 * @returns {Array} - List of orders
 */
const fetchOrderHistory = async (patientId, dateFilter) => {
  return await Order.find({
    customer_id: patientId,
    ...dateFilter,
  })
    .populate({
      path: 'order_items',
      populate: {
        path: 'medicine_id',
        select: 'Name sale_price',
      },
    })
    .populate('branch_id', 'name address')
    .populate('salesperson_id', 'fullName')
    .sort({ created_at: -1 })
    .lean();
};

/**
 * Fetch patient information
 * @param {String} patientId - The patient/customer ID
 * @returns {Object} - Patient details
 */
const fetchPatientInfo = async patientId => {
  return await Customer.findById(patientId)
    .select('fullName email gender dateOfBirth contactNumber profile_img_url')
    .lean();
};

/**
 * Get patient's complete medical history
 * @param {Object} req - Express request object
 * @param {String} patientId - The patient/customer ID
 * @param {String} startDate - Optional start date filter
 * @param {String} endDate - Optional end date filter
 * @returns {Object} - Aggregated medical history
 */
export const getPatientMedicalHistory = async (
  req,
  patientId,
  startDate,
  endDate
) => {
  const doctorId = req.doctor._id;

  // Step 1: Authorization check - ensure doctor has treated this patient
  const isAuthorized = await checkDoctorAuthorization(doctorId, patientId);
  if (!isAuthorized) {
    throw new Error(
      "UNAUTHORIZED_ACCESS: You do not have permission to view this patient's medical history"
    );
  }

  // Step 2: Build date filter
  const dateFilter = buildDateFilter(startDate, endDate);

  // Step 3: Fetch patient information
  const patientInfo = await fetchPatientInfo(patientId);
  if (!patientInfo) {
    throw new Error('PATIENT_NOT_FOUND: Patient not found');
  }

  // Step 4: Fetch all medical data in parallel
  const [appointments, doctorPrescriptions, uploadedPrescriptions, orders] =
    await Promise.all([
      fetchAppointments(patientId, dateFilter),
      fetchDoctorPrescriptions(patientId, dateFilter),
      fetchUploadedPrescriptions(patientId, dateFilter),
      fetchOrderHistory(patientId, dateFilter),
    ]);

  // Step 5: Extract medical notes from appointments
  const medicalNotes = appointments
    .filter(apt => apt.notes && apt.notes.trim() !== '')
    .map(apt => ({
      appointment_id: apt._id,
      appointment_date: apt.created_at,
      appointment_type: apt.appointment_type,
      notes: apt.notes,
      doctor: apt.doctor_id,
    }));

  // Step 6: Log the access for compliance
  await logDoctorActivity(
    req,
    'view_medical_history',
    `Viewed medical history for patient: ${patientInfo.fullName}`,
    'customers',
    patientId,
    {
      filters: { startDate, endDate },
      data_accessed: {
        appointments_count: appointments.length,
        prescriptions_count: doctorPrescriptions.length,
        uploaded_prescriptions_count: uploadedPrescriptions.length,
        orders_count: orders.length,
      },
    }
  );

  // Step 7: Return aggregated data
  return {
    patient: patientInfo,
    summary: {
      total_appointments: appointments.length,
      total_prescriptions_generated: doctorPrescriptions.length,
      total_prescriptions_uploaded: uploadedPrescriptions.length,
      total_orders: orders.length,
      total_medical_notes: medicalNotes.length,
    },
    history: {
      appointments,
      prescriptions_generated_by_doctor: doctorPrescriptions,
      prescriptions_uploaded_by_patient: uploadedPrescriptions,
      orders,
      medical_notes: medicalNotes,
    },
  };
};
